package Model;

/** A BonusLife Powerup for minesweeper
 *  Increases the player's number of lives when applied.
 */
public class BonusLife implements GridItem{

    private int strength;

    /**
     * Constructor for BonusLife
     * @param s strength of the powerup
     */
    public BonusLife(int s){
        strength = s;
    }

    /**
     * Applies the effect of the grid item.
     * @return the number of lives to be regenerated by the player.
     */
    @Override
    public int applygridItem() {
        return strength;
    }
    @Override
    public String toString() {
        return "BonusLife";
    }
}
