package Model;

/** A BonusLife Powerup for minesweeper
 *  Increases the player's number of lives when applied.
 */
public class BonusLife implements GridItem{

    private final int strength;
    public int x;
    public int y;
    public boolean uncovered;

    /**
     * Constructor for BonusLife
     * @param s strength of the powerup
     */
    public BonusLife(int s, int a, int b){
        this.x = a;
        this.y = b;
        this.strength = s;
    }

    /**
     * Applies the effect of the grid item.
     * @return the number of lives to be regenerated by the player, which is the strength of the powerup.
     */
    @Override
    public int applygridItem() {
        return strength;
    }
    @Override
    public String toString() {
        return "BonusLife";
    }
    @Override
    public void uncover() {
        this.uncovered = true;
    }
    public boolean isUncovered() {
        return uncovered;
    }
}
